### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Monkatraz** [TheComputerM/svelte-docster#1]
Heya, saw this project and I love the output format. However, all of my components (and codebase) use TypeScript, and not annotated JS - so unfortunately this library isn't so useful for me.

For me, all I would really want is basically a translation of `foo: string = "bar"` into `/** @type string */ foo = "bar"`, if that makes any sense. I wouldn't need declaration files or anything - just basic support. I know that's more complicated than it sounds - I haven't come empty handed.

I made more own absurd solution to this problem, [which you can find here](https://github.com/scpwiki/wikijump/blob/develop/client/modules/components/doc-gen.js).

It generates an output that looks like this:
```json
{
  "definitions": {
    "IComponentOptions": {
      "type": "object",
      "properties": {
        "target": {
          "ref": "Element"
        },
        "anchor": {
          "ref": "Element"
        },
        "props": {
          "ref": "Record"
        },
        "context": {
          "ref": "Map"
        },
        "hydrate": {
          "type": "boolean"
        },
        "intro": {
          "type": "boolean"
        }
      }
    },
    "IntersectionPoint": {
      "description": "Component that fires callbacks when it comes in and out of view.",
      "type": "object",
      "properties": {
        "props": {
          "type": "object",
          "properties": {
            "onEnter": {
              "description": "Function to call when the observer enters the viewport."
            },
            "onExit": {
              "description": "Function to call when the observer leaves the viewport."
            },
            "opts": {
              "ref": "IntersectionObserverInit",
              "description": "Options for the `IntersectionObserver`."
            }
          }
        },
        "events": {
          "type": "object",
          "additionalProperties": {
            "ref": "CustomEvent<any>"
          }
        },
        "slots": {
          "type": "object"
        }
      }
    }
  }
}
```

And a declaration file:
```ts
export interface IComponentOptions {
    target: Element;
    anchor?: Element;
    props?: Record<string, any>;
    context?: Map<any, any>;
    hydrate?: boolean;
    intro?: boolean;
}
/** Component that fires callbacks when it comes in and out of view. */
export declare class IntersectionPoint {
    constructor(options: IComponentOptions);
    props: typeof props.props;
    events: typeof props.events;
    slots: typeof props.slots;
}
declare const props: {
    props: {
        /** Function to call when the observer enters the viewport. */ onEnter?: any;
        /** Function to call when the observer leaves the viewport.*/ onExit?: any;
        /** Options for the {@link IntersectionObserver}.*/ opts?: IntersectionObserverInit | undefined;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export {};
```

I mention my ad-hoc solution because there is a few tricks you may be able to use to "cheat" and avoid parsing a TS source directly - perhaps you can get the info you need from the TS source, run the preprocessor, and then do normal parsing of the component.

Using `svelte2tsx`, you can process a component and then read the `exportedNames` property from the returned object, which will look like this:
```
exportedNames: ExportedNames(3) [Map] {
  'onEnter' => {
    type: 'AnyFunction',
    identifierText: 'onEnter',
    required: false,
    doc: '/** Function to call when the observer enters the viewport. */'
  },
  'onExit' => {
    type: 'AnyFunction',
    identifierText: 'onExit',
    required: false,
    doc: '/** Function to call when the observer leaves the viewport.*/'
  },
  'opts' => {
    type: 'IntersectionObserverInit',
    identifierText: 'opts',
    required: false,
    doc: '/** Options for the {@link IntersectionObserver}.*/'
  }
}
```

This isn't perfect, as it doesn't infer types:
```
exportedNames: ExportedNames(3) [Map] {
  'height' => {
    type: undefined,
    identifierText: 'height',
    required: false,
    doc: "/** Height of the editor's container. */"
  },
  'width' => {
    type: undefined,
    identifierText: 'width',
    required: false,
    doc: "/** Width of the editor's container.*/"
  },
  'doc' => {
    type: undefined,
    identifierText: 'doc',
    required: false,
    doc: "/** The value of the editor's contents. */"
  }
}
```
But I think you can use an inferred type from normal parsing? I'm sure that isn't too big of an issue.

I also have no idea how the module context is handled here - I don't really use that feature.

I hope this information is of some help to you! If you don't feel like implementing anything like I have described, it would at least be nice if this library supported running the preprocessor naturally (rather than doing it yourself) and then generating documentation.

**Comment by TheComputerM** [comment]
Are you using this lib to generate typings? if so then look into this: https://www.npmjs.com/package/svelte-type-generator

**Comment by Monkatraz** [comment]
No - although I do generate declarations, I'm using them as a way of documenting the components. They're not using `SvelteComponentTyped` or anything.

I'd like to use a library like this to _properly_ document components, which with TS is apparently difficult. e.g. you can't just hookup TypeDoc to the output of `svelte-type-generator` because the result is nigh-incomprehensible.

**Comment by TheComputerM** [comment]
Holy Shit you maintain the SCP Wiki, took me long enough to realize.

**Comment by Monkatraz** [comment]
lol yeah

"Maintain" is a strong word, the actual scp-wiki site is pretty much unmaintained, at least in a sense, because Wikidot as a platform is unmaintained. The project we're working on is a replacement/fork of Wikidot.

**Comment by TheComputerM** [comment]
I will try to get TS to work, the only stuff really affected by typescript are the props right?

**Comment by Monkatraz** [comment]
Yeah, as far as I can tell anyways.

**Comment by TheComputerM** [comment]
I may need to make a seperate package for ts due to additional dependencies.

**Comment by TheComputerM** [comment]
Did you check out sveltedoc-parser, seems they might release typescript support sooner than me.

**Comment by Monkatraz** [comment]
I have - however updates to that project have seemed pretty slow. I made an issue here because 1. there wasn't one yet and 2. I liked the emitted metadata format here a lot.

**Comment by TheComputerM** [comment]
Hey I have added typescript support but it does not work with `module="context"`, it is ok?

**Comment by Monkatraz** [comment]
That's great! I hardly ever use `module="context"` - and I think if you wanna document module context you can just use TS declaration files anyways - so that's fine with me!

**Comment by TheComputerM** [comment]
Do you use cjs or esm to load your files?

**Comment by Monkatraz** [comment]
Everything client-side related is ESM - but build tools tend to get written with CJS. If you're just asking what the Svelte files use for their imports, it is ESM.

**Comment by TheComputerM** [comment]
See version `1.2.1`. I will update to version 1.3.0 when I have tested more and added support for context="module"

**Comment by TheComputerM** [comment]
https://github.com/TheComputerM/svelte-docster#with-typescript

**Comment by Monkatraz** [comment]
Ayy, it works! https://gist.github.com/Monkatraz/30194691e90c9c864f70d8aca700e1fc

Two things I've noticed:
1. I had to correct for Windows being bad and having `\r\n` line terminators. (`code.replaceAll("\r\n", "\n")`)
2. Some obvious types aren't inferred - although I have no idea if in the TS AST that can be easily figured out. Example:
    ```
    "props": {
      "height": {
        "value": "\"100%\"",
        "valueType": "Literal",
        "localName": "height",
        "kind": "let",
        "required": false,
        "description": "Height of the editor's container.",
        "tags": []
      }
     }
     ```

EDIT: I just looked in the code and you're doing what I suggested - yeah, the inferred type thing is probably a bit difficult to figure out without adding a lot of complexity. The doc-gen is light and fast so it's probably not worth it to add that kind of complexity.

**Comment by TheComputerM** [comment]
Will fix tomorrow

**Comment by TheComputerM** [comment]
Fixed, also now you can infer types, it is not that hard, just have to do:
```
        try {
          prop.type = typeof JSON.parse(prop.value);
        } catch {}
```

**Comment by TheComputerM** [comment]
Now just left to add `context="module"` support

**Comment by TheComputerM** [comment]
Not adding ts support as it is only useful for props and you can easily do it yourself:
```js
  const scriptRegex = /<script(.*)>((.|\n)*?)<\/script>/;
  const scriptContentTS = scriptRegex.exec(content)[2];
  const scriptContentJS = sucrase(scriptContentTS, {
    transforms: ["typescript"],
  }).code;

  const docs = docster({
    content: `<script>${scriptContentJS}</script>`,
    filename,
  });

  const tsMetadata = s2tsx(content, { filename, strictMode: false }).exportedNames;
```
